"""Add multiple_choice_options column to Question model

Revision ID: 0943f3f4daf5
Revises: f7a1a446b805
Create Date: 2023-04-10 16:36:16.245693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0943f3f4daf5'
down_revision = 'f7a1a446b805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiple_choice_options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('multiple_choice_options')

    # ### end Alembic commands ###
