"""empty message

Revision ID: 454eef9b3048
Revises: 15c79bb825f6
Create Date: 2023-04-09 12:24:50.882748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454eef9b3048'
down_revision = '15c79bb825f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    # ### end Alembic commands ###
