"""Your migration message 3

Revision ID: f958bc6e2ad7
Revises: 19cfe98f4853
Create Date: 2023-04-09 15:46:56.463638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f958bc6e2ad7'
down_revision = '19cfe98f4853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index('title', ['title'], unique=False)

    # ### end Alembic commands ###
